MyFirstASPNETWebapp1/Models/GradeCalc.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyFirstASPNETWebapp1.Models
{

    public class GradeCalc
    {
        [Required]
        [Range(0, 100)]

        public int Assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public int Group { get; set; }
        [Required]
        [Range(0, 100)]
        public int Quizzes { get; set; }
        [Required]
        [Range(0, 100)]
        public int Exam { get; set; }
        [Required]
        [Range(0, 100)]
        public int Intex { get; set; }

    }
}
    
      

MyFirstASPNETWebapp1/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstASPNETWebapp1.Models;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyFirstASPNETWebapp1.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Calculator()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Calculator(GradeCalc model)
        {
            return View();
        }
    }
}

MyFirstASPNETWebapp1/Views/Blah/Calculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model GradeCalc;
<h2>Calculate your final grade.</h2>
<form method="post">
    <label>Assignments</label>
    <input id="numAssignments" asp-for="Assignments" />
    <br />
    <label>Group Project</label>
    <input id="numGroup" asp-for="Group" />
    <br />
    <label>Quizzes</label>
    <input id="numQuiz" asp-for="Quizzes" />
    <br />

    <label>Exams</label>
    <input id="numExam" asp-for="Exam" />
    <br />
    <label>INTEX</label>
    <input id="numIntex" asp-for="Intex" />
    <br />
    <!--<input id="btnSend" type="button" value="Calulate" />-->
    <button id="btnSend">Submit</button>
    <div asp-validation-summary="All"></div>

</form>
<!--connect jquery page, connect calculator js page.-->

<script src="~/js/calculator.js"></script>

MyFirstASPNETWebapp1/Views/Blah/Index.cshtml
@*
For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Aidan Garry";
}

<!--add title and picture of something I enjoy.-->
<!--ADD NAV BAR-->

<h1>Welcome to my page!:)))!</h1>

<img src="img/aidanyoshsnow.JPEG" width="400px" />
<!--expectations for IS 413-->
<p>
    Aidan Garry is a student at BYU hopelessly trying to a pursue a degree in Information Systems...
    My expectations for IS 413 are to learn more about programming from Prof. Hilton. I am excited to understand C# and the applications that we will be using it in.
    I want to do well in this class after a rough start on getting this program to work on my mac...
</p>
<br />
<!--Top careers I will consider after I gradeuate using a list.-->
<p>Top 3 careers I may pursue in life:</p>
<ul>
    <li>A. Data Scientist</li>
    <li>B. Data Analyst</li>
    <li>c. Systems Analyst</li>
</ul>
<!--using form to take input for calculator.-->
<h2>Calculate your final grade.</h2>
<form>
    <label>Assignments</label>
    <input id="numAssignments" />
    <br />
    <label>Group Project</label>
    <input id="numGroup" />
    <br />
    <label>Quizzes</label>
    <input id="numQuiz" />
    <br />

    <label>Exams</label>
    <input id="numExam" />
    <br />
    <label>INTEX</label>
    <input id="numIntex" />
    <br />
    <input id="btnSend" type="button" value="Calulate" />

</form>
<!--connect jquery page, connect calculator js page.-->
    
<script src="~/js/calculator.js"></script>

MyFirstASPNETWebapp1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/default.css" rel="stylesheet" />
    <link rel="icon" href="~/img/icon.jpg">
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery-3.6.0.min.js"></script>
</head>
<body>

    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="Calculator">Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>


    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    
</body>
</html>